### ISSUE TITLE
Testnet Seeds are Weak/Repetitive

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianWallet-iOS#121]
My first Hot wallet seed was: cactus/abandon/abandon/abandon/abandon/gate/acoustic/magic/library/avoid/abandon/light

I then created a warm wallet.
The node seed was: 

1. cactus
2. abandon
3. abandon
4. abandon
5. abandon
6. gate
7. accuse
8. gym
9. length
10. avoid
11. abandon
12. liar

The offline seed was:

1. cactus
2. abandon
3. abandon
4. abandon
5. abandon
6. gather
7. achieve
8. praise
9. length
10. avoid
11. abandon
12. license

**Comment by wolfmcnally** [comment]
This output clearly looks wrong. The first thing I want to know is: is the issue replicable? If it is, then Peter should just track it down and fix it. The second question I had was: is this problem with seed generation itself, or the export of seeds to BIP39? This could be determined by round-tripping: putting the BIP39 sequences above back in and seeing whether you get the same key back out. If you do, the error is in seed generation, and if you don’t then the error is in seed export.

**Comment by Fonta1n3** [comment]
[https://github.com/BlockchainCommons/GordianWallet-iOS/pull/111/commits/bb140abda200f75e3875fef5723f2efa207a1612](https://github.com/BlockchainCommons/GordianWallet-iOS/pull/111/commits/bb140abda200f75e3875fef5723f2efa207a1612) fixes this. If it is still an issue for you please reopen. Will push v0.2.8 to TestFlight.

The issue was caused by rushing to update the app for the latest BCLibwallySwift and not having time to do any testing. As you can see https://github.com/BlockchainCommons/GordianWallet-iOS/pull/111/commits/bb140abda200f75e3875fef5723f2efa207a1612 is a large commit, it has not been well tested so there very well may be other bugs. Until more testing is done I will be keeping the Testflight to internal testers only.
