### ISSUE TITLE
[Bug]: Two nodes active at the same time

### ISSUE THREAD

**Issue by ben-kaufman** [BlockchainCommons/GordianWallet-iOS#58]
Using Standup.app, I tried to connect FN2 to my mainnet and testnet nodes, but somehow after adding both and toggling between them the app has just left both on and wouldn't allow me to disable any of them, saying one node must be active. Deleting the nodes and readding them solved the issue at least partially.

How to reproduce:
1. In the node manager, connect to mainnet node.
2. In the node manager, connect to testnet node.
3. Toggle the mainnet node on.
4. Toggle the testnet node on.
(Note: sometimes clicking on the toggle requested me to "Update this node". So then I rescanned the QuickConnect QR as it prompted me to, that might be related).

**Comment by Fonta1n3** [comment]
Thanks for submitting an issue, will certainly have a look and get that fixed. In the short term you should be able to force quit the app and reopen.

There is a couple things going on. You can tap the node to get the option to "update" it or "share" it, you can also toggle it on/off. You certainly do not need to update it, that is only there incase you refresh your onion credentials server side and need to update them client side.

It is probably too easy to accidentally tap the node when toggling it so we ought to separate these functions in the UI to designated buttons rather than utilizing `didselectrowat`.

**Comment by Fonta1n3** [comment]
Fixed as per #72
