### ISSUE TITLE
Cannot Import Watch-Only from Specter-Desktop

### ISSUE THREAD

**Issue by mflaxman** [BlockchainCommons/GordianWallet-iOS#96]
Steps:
1. Create multisig wallet on Specter-Desktop:
2. Open Gordian iOS and click on `Accounts` tab.
3. Click on QR icon in upper left and scan `Export Wallet` QR code from Specter-Desktop (http://127.0.0.1:25441/wallets/WALLETNAMEHERE/settings/)

![Screen Shot 2020-10-08 at 10 48 54 AM](https://user-images.githubusercontent.com/448644/95482611-f4dd2000-0953-11eb-8f5d-b1b2b914b121.png)

```{ "label": "Cobo Seedpicker Generated", "blockheight": 1859308, "descriptor": "wsh(sortedmulti(1,[c7d0648a\/48h\/1h\/0h\/2h]tpubDEpefcgzY6ZyEV2uF4xcW2z8bZ3DNeWx9h2BcwcX973BHrmkQxJhpAXoSWZeHkmkiTtnUjfERsTDTVCcifW6po3PFR1JRjUUTJHvPpDqJhr\/0\/*,[f7d04090\/48h\/1h\/0h\/2h]tpubDF7FTuPECTePubPXNK73TYCzV3nRWaJnRwTXD28kh6Fz4LcaRzWwNtX153J7WeJFcQB2T6k9THd424Kmjs8Ps1FC1Xb81TXTxxbGZrLqQNp\/0\/*))#sa6r7elh" }```

4. Hangs on "processing..." forever (restarting the app doesn't help):
![83B8C73D-EC46-4599-A13F-7D2B5E830E52_1_105_c](https://user-images.githubusercontent.com/448644/95482864-32da4400-0954-11eb-89c4-c11f39e39cdb.jpeg)

My use-case is ultimately that I want to see if I can use Gordian as a cosigner in a multisig wallet, but for now I'm seeing if it can just do receive address validation (no private keys).

**Comment by Fonta1n3** [comment]
@mflaxman looks like that is a bug, will push a fix today.

For now in order to achieve your goal you can tap the `+` button in top right corner of Accounts > `Recover` > `Scan Account Map`. Just tested with your wallet QR and it works without issue.

Just a warning about a known lag point, when the app initiates a rescan on your node it can hang for a few seconds so be patient when it says "initiating rescan", I will also push a fix for that today.

**Comment by Fonta1n3** [comment]
And to use Gordian as a signer for this quorum, you:
1. Accounts > tap your account to "activate it"
2. Tap the tools button in top right
3. Tap add a signer

**Comment by Fonta1n3** [comment]
@mflaxman @ChristopherA This bug was introduced when I added UR support to the QR scanner on the Account's view. Often UR QR code payload is uppercased but needs to be converted to lowercase. I had forgotten to remove the forced lowercase for *non* UR QR codes. #97 fixes this bug, should have an update for testflight by the end of today.

**Comment by mflaxman** [comment]
Thanks! happy to try again once the new version is available on testflight.

**Comment by Fonta1n3** [comment]
> Thanks! happy to try again once the new version is available on testflight.

Excellent, keep an eye out for 0.1.88 which includes the fix should be live in next 24 hours.

**Comment by Fonta1n3** [comment]
@mflaxman 0.1.88 is live which fixes this issue, closing for now, if its still a problem feel free to reopen.

**Comment by mflaxman** [comment]
Wohooo, importing watch-only now works!

The UI is quite confusing and it's extremely slow, but it does appear possible.
